function simConst = initSim(simulation)
    switch simulation
        case 'simple'
            simConst = struct(...
                        'damping',   0.01,...
                        'stiffness', 0.5,...
                        'spX0',      0.6,...
                        'mass',      30,...
                        'particles', [-2:2:2]'...
                       );
        case 'inverse'
            simConst = struct(...
                        'damping',   0.1,...
                        'stiffness', 0.5,...
                        'spX0',      0.52,...
                        'mass',      30,...
                        'particles', [-2:2:2]'...
                       );
        case 'multiscale'
            simConst = struct(...
                        'damping',   0.01,...
                        'stiffness', 0.5,...
                        'spX0',      0.6,...
                        'mass',      30,...
                        'particles', [-2:0.5:1.99, 2:0.15:2.99, 3:0.5:6.99]'...
                       );
        otherwise
            simConst = struct(...
                        'damping',   0.5,...
                        'stiffness', 0.5,...
                        'spX0',      0.785,...
                        'mass',      30,...
                        'particles', [-2:0.5:1.99, 2:0.15:2.99,3:0.5:6.99]'...
                       );
end
